services:
    ambta_doctrine_encrypt.orm_subscriber:
        class: Ambta\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: [ "%ambta_doctrine_encrypt.encryptor_class_name%", "%ambta_doctrine_encrypt.secret_key%", "%ambta_doctrine_encrypt.encrypted_suffix%"]
        tags:
            -  { name: doctrine.event_subscriber }
    ambta_doctrine_encrypt.subscriber:
        alias: ambta_doctrine_encrypt.orm_subscriber
    ambta_doctrine_encrypt.encryptor:
        class: Ambta\DoctrineEncryptBundle\Services\Encryptor
        arguments:
            - "%ambta_doctrine_encrypt.encryptor_class_name%"
            - "%ambta_doctrine_encrypt.secret_key%"
            - "%ambta_doctrine_encrypt.encrypted_suffix%"

    ambta_dcotrin_encrypt.encrypt_command:
        class: Ambta\DoctrineEncryptBundle\Command\DoctrineEncryptDatabaseCommand
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@ambta_doctrine_encrypt.orm_subscriber'
            - '@annotations.reader'
        tags:
            - { name: 'console.command' }

    ambta_dcotrin_encrypt.deencrypt_command:
        class: Ambta\DoctrineEncryptBundle\Command\DoctrineDecryptDatabaseCommand
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@ambta_doctrine_encrypt.orm_subscriber'
            - '@annotations.reader'
        tags:
            - { name: 'console.command' }

    ambta_dcotrin_encrypt.encrypt_status_command:
        class: Ambta\DoctrineEncryptBundle\Command\DoctrineEncryptStatusCommand
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@ambta_doctrine_encrypt.orm_subscriber'
            - '@annotations.reader'
        tags:
            - { name: 'console.command' }